### ISSUE TITLE
Check status code logic is a bit severe

### ISSUE THREAD

**Issue by alberto-bottarini** [ddliu/gulp-remote-src#6]
Hi, I'm using gulp-remote-src to trigger jenkins tasks via http request.
When everything is ok, Jenkins responds with a 201 response but i get a fail message about status code "failed with status code:201".

Why are you checking exactly if it's 200? Wouldn't it be better if it checks only if statusCode starts with "2"?

**Comment by ddliu** [comment]
It's originally used for download purpose, so I  only considered 200.

Sure 2xx looks OK as well. I'll add them.

**Comment by alberto-bottarini** [comment]
:+1: :+1: :+1: :+1:
