### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by ivanstan** [ddliu/gulp-remote-src#7]
I am trying to load remote files from multiple cdns.
Is it possible to give absolute path and ommit base parameter? Could we make this a feature if not?

**Comment by ddliu** [comment]
I think we can merge them with other Gulp plugins. Have you tried [merge2](https://github.com/teambition/merge2) or [merge-stream](https://github.com/grncdr/merge-stream)?

**Comment by ivanstan** [comment]
Yes I had thank you. But I thought that it would be handy if I could to this:

```
remoteSrc(["http://www.example.com/test.js", "http://www.someotherdomain.com/test.js"])
```

in this case base path would be '/', so it would be prepended to urls, making invalid requests like:

```
/http://www.example.com/test.js
/http://www.someotherdomain.com/test.js
```

Perhaps we could add validation and not prepend base path for urls starting with http or https?

**Comment by KernowCode** [comment]
I am also trying to get a resource with appended query parameters but it fails i.e ?someparam=somevalue&etc=more
