### ISSUE TITLE
Question: how to access the contents of files after remoteSrc

### ISSUE THREAD

**Issue by ayyash** [ddliu/gulp-remote-src#9]
I am trying to access the contents of every file retrieved to modify things in it, I got stuck and don't know where to start, any pointers?

 remoteSrc(["files"], {
            base: "baseurl"
        }).pipe(do something with file content);

**Comment by ddliu** [comment]
There is no much difference to `gulp.src`. You can refer to gulp plugin guides, or check out source code of other Gulp plugins.
